// Temporary, standalone diagnostic script — not part of the pipeline, not committed.
// Calls the REAL, unmodified generateFlashcards() with a "spy" LLMCaller capturing the
// full StepResult. No production code modified.
import { config as loadEnv } from "dotenv";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import {
  createGeminiTransport,
  createLLMCaller,
  generateFlashcards,
  type Requirement,
  type Question,
  type LLMCaller,
  type StepResult,
} from "@trao/core";
import type { z } from "zod";

const __dirname = dirname(fileURLToPath(import.meta.url));
loadEnv({ path: resolve(__dirname, ".env") });

// Real, validated requirements from the earlier extraction test.
const REQUIREMENTS: Requirement[] = [
  { id: "r1", text: "5+ years of experience with Node.js", kind: "technical", priority: "must", evidence: "5+ years of experience with Node.js is required" },
  { id: "r2", text: "Strong understanding of relational databases", kind: "technical", priority: "must", evidence: "Strong understanding of relational databases is required" },
  { id: "r3", text: "Experience with GraphQL", kind: "technical", priority: "nice", evidence: "Experience with GraphQL is a nice to have" },
];

// Real, validated questions generated by the earlier successful Technical category test.
const QUESTIONS: Question[] = [
  {
    id: "q1",
    requirement_ids: ["r1", "r2"],
    category: "technical",
    prompt: "In a high-throughput Node.js microservice handling e-commerce order checkouts, we are encountering database connection pool exhaustion and intermittent deadlocks during concurrent stock deductions. How would you diagnose, fix, and architect the service and relational database transaction strategy to resolve this?",
    answer_outline: "1. Diagnosis: Inspect pool metrics, slow query logs, and active locks/transactions (e.g., pg_stat_activity). 2. Node.js optimization: Keep transactions as short as possible; never perform external async network calls or heavy business logic within an active DB transaction; properly tune connection pool limits relative to worker threads/cluster instances. 3. DB Locking & Concurrency: Address deadlocks by ensuring uniform resource acquisition order, using atomic conditional updates, or using optimistic locking.",
    difficulty: 3,
    origin: "ai",
    isLocked: false,
  },
  {
    id: "q2",
    requirement_ids: ["r1", "r2", "r3"],
    category: "technical",
    prompt: "When designing a GraphQL API in Node.js backed by a relational database, how do you mitigate the N+1 query problem, and how does DataLoader leverage the Node.js event loop under the hood?",
    answer_outline: "1. N+1 Problem: naive resolver execution triggers individual queries per parent item. 2. DataLoader & Event Loop: DataLoader batches keys within a single tick to execute a single WHERE id IN (...) SQL query, with per-request memoization caching. 3. Protection: query depth limiting, complexity analysis, pagination limits.",
    difficulty: 2,
    origin: "ai",
    isLocked: false,
  },
  {
    id: "q3",
    requirement_ids: ["r1"],
    category: "technical",
    prompt: "A production Node.js service is reporting degraded throughput, high event-loop lag, and eventual Out-Of-Memory (OOM) crashes under sustained load. How would you systematically diagnose the root cause?",
    answer_outline: "Use perf_hooks (eventLoopUtilization/monitorEventLoopDelay), CPU profilers, and heap snapshots to detect retained objects/unbounded caches/unremoved listeners; check for backpressure in streaming I/O; remediate via worker threads and bounded caches.",
    difficulty: 3,
    origin: "ai",
    isLocked: false,
  },
];

async function main() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.log("RESULT: GEMINI_API_KEY is not set — nothing to test.");
    return;
  }

  const transport = createGeminiTransport({
    apiKey,
    model: process.env.GEMINI_MODEL,
    baseUrl: process.env.GEMINI_BASE_URL,
  });
  const realCall = createLLMCaller(transport);

  let captured: StepResult<unknown> | null = null;
  const spyCall: LLMCaller = async <T>(prompt: string, schema: z.ZodType<T>) => {
    const result = await realCall(prompt, schema);
    captured = result as StepResult<unknown>;
    return result;
  };

  console.log(`Model: ${process.env.GEMINI_MODEL?.trim() || "(default) gemini-3.8-flash"}`);
  console.log("Calling the real generateFlashcards() with an instrumented LLMCaller...\n");

  const start = Date.now();
  const flashcards = await generateFlashcards(REQUIREMENTS, QUESTIONS, spyCall);
  const elapsedMs = Date.now() - start;

  console.log(`Elapsed: ${elapsedMs}ms\n`);
  console.log("=== Captured StepResult (null if the real call was never reached, e.g. requirements.length === 0) ===");
  console.log(JSON.stringify(captured, null, 2));

  console.log("\n=== generateFlashcards' actual returned Flashcard[] ===");
  console.log(JSON.stringify(flashcards, null, 2));

  console.log("\n=== Cross-check: requirement_ids vs known supplied ids ===");
  const knownIds = new Set(REQUIREMENTS.map((r) => r.id));
  for (const f of flashcards) {
    const allValid = f.requirement_ids.every((id) => knownIds.has(id));
    console.log(`${f.id}: requirement_ids=${JSON.stringify(f.requirement_ids)} — all reference known requirements: ${allValid}`);
  }
  console.log(`\nTotal flashcards generated: ${flashcards.length}`);
  console.log(`origin field on returned flashcards: ${[...new Set(flashcards.map((f) => f.origin))].join(", ")}`);
}

main().catch((err) => {
  console.error("Flashcard generation test threw an unexpected error:", err);
  process.exitCode = 1;
});
